# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AselMainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Asel(object):
    def setupUi(self, Asel):
        Asel.setObjectName("Asel")
        Asel.setEnabled(True)
        Asel.resize(560, 440)
        Asel.setStyleSheet("background-color: rgb(51,51,51);")
        self.centralwidget = QtWidgets.QWidget(Asel)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 561, 440))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.chatFrame = QtWidgets.QWidget()
        self.chatFrame.setObjectName("chatFrame")
        self.sendMsgButton = QtWidgets.QPushButton(self.chatFrame)
        self.sendMsgButton.setGeometry(QtCore.QRect(490, 390, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sendMsgButton.setFont(font)
        self.sendMsgButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px rgb(60,60,60);\n"
"    color: white;\n"
"    font-size:12;\n"
"    highlight: white;\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80,80,80);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40,40,40);\n"
"}")
        self.sendMsgButton.setObjectName("sendMsgButton")
        self.msgLine = QtWidgets.QLineEdit(self.chatFrame)
        self.msgLine.setGeometry(QtCore.QRect(210, 390, 271, 41))
        self.msgLine.setStyleSheet("background-color: rgb(35,35,35);\n"
"border: 1px rgb(35,35,35);\n"
"color: white;\n"
"border-radius:5px")
        self.msgLine.setText("")
        self.msgLine.setObjectName("msgLine")
        self.textBox = QtWidgets.QTextEdit(self.chatFrame)
        self.textBox.setGeometry(QtCore.QRect(210, 10, 341, 371))
        self.textBox.setStyleSheet("\n"
"background-color: rgb(35,35,35);\n"
"border: 1px rgb(60,60,60);\n"
"color: white;\n"
"font-size:12;\n"
"highlight: white;\n"
"border-radius:10px")
        self.textBox.setReadOnly(True)
        self.textBox.setObjectName("textBox")
        self.frame = QtWidgets.QFrame(self.chatFrame)
        self.frame.setGeometry(QtCore.QRect(10, 50, 191, 331))
        self.frame.setStyleSheet("\n"
"background-color: rgb(35,35,35);\n"
"border: 1px rgb(60,60,60);\n"
"color: white;\n"
"font-size:12;\n"
"highlight: white;\n"
"border-radius:10px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.friendBox1 = QtWidgets.QPushButton(self.frame)
        self.friendBox1.setGeometry(QtCore.QRect(10, 10, 171, 31))
        self.friendBox1.setStyleSheet("QPushButton{\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px rgb(60,60,60);\n"
"    color: white;\n"
"    font-size:12;\n"
"    highlight: white;\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80,80,80);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40,40,40);\n"
"}")
        self.friendBox1.setObjectName("friendBox1")
        self.friendBox6 = QtWidgets.QPushButton(self.frame)
        self.friendBox6.setGeometry(QtCore.QRect(10, 210, 171, 31))
        self.friendBox6.setStyleSheet("QPushButton{\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px rgb(60,60,60);\n"
"    color: white;\n"
"    font-size:12;\n"
"    highlight: white;\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80,80,80);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40,40,40);\n"
"}")
        self.friendBox6.setObjectName("friendBox6")
        self.friendBox5 = QtWidgets.QPushButton(self.frame)
        self.friendBox5.setGeometry(QtCore.QRect(10, 170, 171, 31))
        self.friendBox5.setStyleSheet("QPushButton{\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px rgb(60,60,60);\n"
"    color: white;\n"
"    font-size:12;\n"
"    highlight: white;\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80,80,80);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40,40,40);\n"
"}")
        self.friendBox5.setObjectName("friendBox5")
        self.friendBox2 = QtWidgets.QPushButton(self.frame)
        self.friendBox2.setGeometry(QtCore.QRect(10, 50, 171, 31))
        self.friendBox2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px rgb(60,60,60);\n"
"    color: white;\n"
"    font-size:12;\n"
"    highlight: white;\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80,80,80);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40,40,40);\n"
"}")
        self.friendBox2.setObjectName("friendBox2")
        self.friendBox4 = QtWidgets.QPushButton(self.frame)
        self.friendBox4.setGeometry(QtCore.QRect(10, 130, 171, 31))
        self.friendBox4.setStyleSheet("QPushButton{\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px rgb(60,60,60);\n"
"    color: white;\n"
"    font-size:12;\n"
"    highlight: white;\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80,80,80);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40,40,40);\n"
"}")
        self.friendBox4.setObjectName("friendBox4")
        self.friendBox3 = QtWidgets.QPushButton(self.frame)
        self.friendBox3.setGeometry(QtCore.QRect(10, 90, 171, 31))
        self.friendBox3.setStyleSheet("QPushButton{\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px rgb(60,60,60);\n"
"    color: white;\n"
"    font-size:12;\n"
"    highlight: white;\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80,80,80);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40,40,40);\n"
"}")
        self.friendBox3.setObjectName("friendBox3")
        self.friendBox7 = QtWidgets.QPushButton(self.frame)
        self.friendBox7.setGeometry(QtCore.QRect(10, 250, 171, 31))
        self.friendBox7.setStyleSheet("QPushButton{\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px rgb(60,60,60);\n"
"    color: white;\n"
"    font-size:12;\n"
"    highlight: white;\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80,80,80);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40,40,40);\n"
"}")
        self.friendBox7.setObjectName("friendBox7")
        self.friendBox8 = QtWidgets.QPushButton(self.frame)
        self.friendBox8.setGeometry(QtCore.QRect(10, 290, 171, 31))
        self.friendBox8.setStyleSheet("QPushButton{\n"
"    background-color: rgb(35,35,35);\n"
"    border: 1px rgb(60,60,60);\n"
"    color: white;\n"
"    font-size:12;\n"
"    highlight: white;\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80,80,80);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40,40,40);\n"
"}")
        self.friendBox8.setObjectName("friendBox8")
        self.userLine = QtWidgets.QLineEdit(self.chatFrame)
        self.userLine.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.userLine.setStyleSheet("background-color: rgb(35,35,35);\n"
"border: 1px rgb(35,35,35);\n"
"color: white;\n"
"border-radius:5px")
        self.userLine.setText("")
        self.userLine.setObjectName("userLine")
        self.callButton = QtWidgets.QPushButton(self.chatFrame)
        self.callButton.setGeometry(QtCore.QRect(520, 20, 21, 21))
        self.callButton.setToolTip("")
        self.callButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(48, 214, 76);\n"
"    border: 1px rgb(60,60,60);\n"
"    color: lime;\n"
"    font-size:12;\n"
"    highlight: white;\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80,80,80);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40,40,40);\n"
"}")
        self.callButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../../../../OneDrive/Desktop/AselIcons/phone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.callButton.setIcon(icon)
        self.callButton.setObjectName("callButton")
        self.stackedWidget.addWidget(self.chatFrame)
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Asel = QtWidgets.QMainWindow()
    ui = Ui_Asel()
    ui.setupUi(Asel)
    Asel.show()
    sys.exit(app.exec_())
